version: '2.0'

services:
  dataflow:
    image: dataflow
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/container/app
    #command:  nodemon --inspect=0.0.0.0:9229 --inspect-brk main.js
    command: npm run watch
  